EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H

IDINT0 EQU 10

PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H

ORG 1000H
  FLAG DB 0
  LONGITUD DB 0
  CADENA DB ?

ORG 40
DIR_RUT DW RUT_F10

ORG 3000H
; CANCELAR INTERRUPCIONES FUTURAS
RUT_F10: MOV AL, 0FFH
         OUT IMR, AL
; INDICAMOS AL PROGRAMA QUE NO LEA MAS
         MOV FLAG, 1
         MOV AL, 20H
         OUT EOI, AL
         IRET 
ORG 2000H
CLI
; INICIALIZACION PIO PARA IMPRESORA
MOV AL, 0FDH
OUT CA, AL
MOV AL, 0
OUT CB, AL
IN AL, PA
AND AL, 0FDH
OUT PA, AL
; INICIALIZACION DEL PIC
MOV AL, 0FEH ; FE= 1111 1110
OUT IMR, AL
MOV AL, IDINT0
OUT INT0, AL
STI

; LECTURA DE CADENA
MOV BX, OFFSET CADENA
LOOP: INT 6 ; LEER CHAR
INC BX
INC LONGITUD
CMP FLAG, 0 ; VERIFICO SI PRESIONARON F10
JZ LOOP

; IMPRESION DE LOS CARACTERES LEIDOS
MOV BX, OFFSET CADENA ; REINICIAR PUNTERO AL COMIENZO
POLL: NOP
IN AL, PA
AND AL, 1
JNZ POLL
; ENVIAR CARACTER
MOV AL, [BX]
OUT PB, AL
; PULSO STROBE
IN AL, PA
OR AL, 02H
OUT PA, AL
; REINICIAR STROBE
IN AL, PA
AND AL, 0FDH
OUT PA, AL
; PASAR AL SIGUIENTE CHAR
INC BX
DEC LONGITUD
JNZ POLL
INT 0
END
