PIC EQU 20H
HAND EQU 40H
N_HND EQU 10

ORG 40
IP_HND DW RUT_HND

ORG 3000H
RUT_HND: PUSH AX
         INT 6
         MOV AL, [BX] ; CARACTER
         OUT HAND, AL ; REGISTRO DE DATO 40H
         INC BX   
         DEC CL 
         JNZ FINAL
LOOP:    DEC BX
         MOV AL, [BX]
         OUT HAND, AL
         CMP BX, 1000H
         JNZ LOOP
         MOV AL, 0FFH ; DESENMASCARAS EL PIC LA PARTE DEL INT2 HANDSHAKE LO DESHABILITA
         OUT PIC+1, AL
FINAL:   MOV AL, 20H ; END OF INTERRUPTION 
         OUT PIC, AL ; END OF INTERRUPTION 
         POP AX
         IRET

ORG 1000H
MSJ DB ?

ORG 2000H
  MOV BX, OFFSET MSJ
  MOV CL, 5
  CLI
  MOV AL, 0FBH ; 1111 1011 ; INT2 HANDSHAKE
  OUT PIC+1, AL ; CONFIGURO PIC
  MOV AL, N_HND
  OUT PIC+6, AL
  MOV AL, 80H ; CONFIG HANDSHAKE ; 1000 0000 ; 1 EN BIT INT 
  OUT HAND+1, AL
  STI
LAZO: CMP CL, 0
  JNZ LAZO
  IN AL, HAND+1 
  AND AL, 7FH ; XXXX XXXX AND 0111 1111 = 0XXX XXXX
  OUT HAND+1, AL 
INT 0
END
